import { StackScreenProps } from '@react-navigation/stack';
import React from 'react';// Generated by https://quicktype.io

import { Text, View, Image, StyleSheet, Dimensions, ActivityIndicator } from 'react-native';
import { ScrollView } from 'react-native-gesture-handler';
//import { Movie } from '../interfaces/movieInterface';
import { RootStackParams } from '../navigation/Navigation';

//import Icon from 'react-native-vector-icons/Ionicons';
import { useMovieDetails } from '../hooks/useMovieDetails';
import { MovieDetails } from '../components/MovieDetails';

const screenHeight = Dimensions.get('screen').height

interface Props extends StackScreenProps<RootStackParams, 'DetailScreen'> { }

export const DetailScreen = ({ route }: Props) => {

  const movie = route.params;
  const uri = `https://image.tmdb.org/t/p/w500${movie.poster_path}`;

  //console.log(movie.id)

  const {isLoading, cast, movieFull} = useMovieDetails(movie.id);

  console.log(isLoading)







  console.log(movie.title);
  return (
    <ScrollView>
      <View style={styles.imageContainer}>
        <View style={styles.imageBorder}>
          <Image source={{ uri }} style={styles.posterImage} />
        </View>
      </View>
      <View style={styles.marginContainer}>
        <Text style={styles.subTitle}>{movie.original_title}</Text>
        <Text style={styles.title}>{movie.title}</Text>
      </View>

      <View>

        {
          isLoading 
          ?  <ActivityIndicator size={30} color="grey" style={{marginTop: 20}} /> 
          : <MovieDetails movieFull={movieFull!} cast={cast} />
        }
       
      {/* <Icon name="star-outline" size={20} color="grey" /> */}
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  imageContainer: {
    /*  backgroundColor: 'red', */
    //overflow: 'hidden',
    width: '100%',
    height: screenHeight * 0.7,
    paddingBottom: 15,
    /* shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.24,
    shadowRadius: 7,

    elevation: 9, */
    /* borderBottomEndRadius: 5,
    borderBottomStartRadius: 5, */
  },
  imageBorder: {
    flex: 1,
    overflow: 'hidden',
    borderBottomEndRadius: 25,
    borderBottomStartRadius: 25,
  },
  posterImage: {
    flex: 1,
  },
  marginContainer: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  subTitle: {
    fontSize: 16,
    opacity: 0.8,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold'
  }
});
