import React from 'react';// Generated by https://quicktype.io

import { Text, View } from 'react-native';


export const DetailScreen = () => {
  return (
    <View>
        <Text>DetailScreen</Text>
        </View>
  );
};
